language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vit271202/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vit271202/react-test npm test -- --coverage

after_success:
  - docker build -t vit271202/multi-client ./client
  - docker build -t vit271202/multi-nginx ./nginx
  - docker build -t vit271202/multi-server ./server
  - docker build -t vit271202/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vit271202/multi-client
  - docker push vit271202/multi-nginx
  - docker push vit271202/multi-server
  - docker push vit271202/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-421430921195
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  